### ISSUE TITLE
An error occurred during the execution of step “make -j4”

### ISSUE THREAD

**Issue by Shane-Bambu** [junanita/matfp#1]
Hello, I am getting the following error while configuring this project on my MacBook Air(M2). How can I fix this error?

In file included from /github/matfp/extern/geogram/src/lib/geogram/basic/process_unix.cpp:75:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/xmmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"

**Comment by ningnawang** [comment]
It seems like a compiling issue of `geogram`, you may want to check if `geogram` is compatible with M2 chip (https://github.com/BrunoLevy/geogram). This code is tested on M1 chip only.

**Comment by Shane-Bambu** [comment]
I got the same error on my classmate's MacBook Pro (M1 Pro). So I guess it's not because of the chip, maybe the version of geogram is wrong?

**Comment by Shane-Bambu** [comment]
After changing the `geogram` version and commenting the `matfp/src/matfp/external/WindingNumber.h` file, I successfully ran this project on my MacBook Air(M2). Thanks!

**Comment by Frank-ZY-Dou** [comment]
> After changing the `geogram` version and commenting the `matfp/src/matfp/external/WindingNumber.h` file, I successfully ran this project on my MacBook Air(M2). Thanks!

Hey! Could you give more details on how you changed the version of Geogram in your project?
